cts.json

Fixes https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/issues/5

Allow lower case hex in unicode escapes

---

cts.json

Non-deterministic cases are deferred.
Fixes https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/issues/7
This PR assumes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/215 will be resolved by https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/218. We should defer merging this PR until https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/218 lands.

Test descendant selector

---

cts.json

Please correct me if I'm wrong, but the standard seems to allow the name shorthands to start from (and consist of) an underscore.
https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/draft-ietf-jsonpath-base.html#name-syntax-8
```ABNF
child-segment             = bracketed-selection /
("."
(wildcard-selector /
member-name-shorthand))
bracketed-selection       = "[" S selector *(S "," S selector) S "]"
member-name-shorthand     = name-first *name-char
name-first                = ALPHA /
"_"   /            ; _
%x80-10FFFF
; any non-ASCII Unicode character
name-char                 = DIGIT / name-first
DIGIT                     =  %x30-39              ; 0-9
ALPHA                     =  %x41-5A / %x61-7A    ; A-Z / a-z
```

Allow underscores in member name shorthand

---

cts.json

I think this should round out the current syntax for expressions
Resolves #8 
Relates to spec repo issues [#360](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/360), [#361](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/361), [#362](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/362), [#367](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/367), and [#368](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/368).  Most of these have been created as a result of this PR.

Added cases for filter functions

---

cts.json

To cover the cases where the regexp comes from the same document.
I hope you don't mind the autoformat.

Add more tests for search() and match().

---

.github/workflows/validate_json_schema.yaml
build.js
build.sh
cts.json
tests/basic.json
tests/filter.json
tests/functions/count.json
tests/functions/length.json
tests/functions/match.json
tests/functions/search.json
tests/functions/value.json
tests/index_selector.json
tests/name_selector.json
tests/slice_selector.json

An attempt to split the CTS into manageable pieces. The individual test suites are in the `tests` directory. The `build.sh` reads the `tests` recursively and places the result into `cts.json`. The directory/file names are prepended to the test names and the underscores are replaced with spaces.
The resulting `cts.json` is included with the PR. It is possible to build the `cts.json` automatically in a GitHub action later.
Since the resulting `cts.json` is different from the original (the names of some tests have changed, the tests are reordered), here's a simple script to compare the before/after:
```javascript
const fs = require('fs');
const tests = JSON
.parse(fs.readFileSync(0).toString())
.tests;
tests.forEach(test => delete test.name);
tests.sort((a, b) => …
```

Test suite split PoC

---

build.ps1
build.sh
cts.json
tests/basic.json
tests/functions/count.json
tests/functions/length.json
tests/whitespace/functions.json
tests/whitespace/operators.json
tests/whitespace/selectors.json
tests/whitespace/slice.json

Resolves #16
I haven't pushed the _cts.json_ changes, though I was able to rebuild it locally.  Not sure if that's done automatically yet.  If not, I'll go ahead and push those changes.
Supported whitespace includes
- space
- tab
- carriage return
- newline
These tests check all of those.  ~My implementation doesn't seem to like some of them yet.  Haven't been able to test whether that's my implementation or something about the way I wrote the tests.  Will continue to check.~

whitespace tests and some others

---

cts.json
tests/whitespace/selectors.json

Modified tests/whitespace/selectors.json to change those tests that were marking paths with whitespace between the root '$' and the selector as invalid.  Rebuilt and committed cts.json as part of this. #40

Fix for #40 Whitespace allowed between root and selector

---

cts.json
tests/whitespace/filter.json

Cover whitespace in and around filter selectors. Closes #44.
I note that there is arguably nothing special about whitespace around parenthesized expressions, and choosing to test cases such as "space between question mark and parenthesized expression" might be considered a little arbitrary, compared to any other filter expression not surrounded by parentheses.
Similarly, one might consider there to be unnecessary overlap between "space between bracket and question mark" etc. and cases from `whitespace/selectors.json`.  I would understand if these test cases need to be removed.

Cover whitespace in and around filter selectors

---

cts.json
tests/basic.json
tests/filter.json

Cover multiple selectors including filters and wildcards. Closes #45.

Cover multiple selectors inc filters and wildcards

---

cts.json
tests/whitespace/operators.json

Cover whitespace between the logical not operator and a test expression or parenthesized expression.
For reference, this is the relevant part of the grammar.
```plain
paren-expr          = [logical-not-op S] "(" S logical-expr S ")"
; parenthesized expression
logical-not-op      = "!"               ; logical NOT operator
test-expr           = [logical-not-op S]
(filter-query / ; existence/non-existence
function-expr) ; LogicalType or
; NodesType
```

Cover whitespace between logical not and expr

---

cts.json
tests/name_selector.json

Cover name selectors that are an empty string literal. Like `$['']` and `$[""]`.

Cover empty name selectors

---

cts.json
tests/filter.json

For reference, this is the relevant part of the grammar.
```plain
literal             = number / string-literal /
true / false / null
number              = (int / "-0") [ frac ] [ exp ] ; decimal number
frac                = "." 1*DIGIT                  ; decimal fraction
exp                 = "e" [ "-" / "+" ] 1*DIGIT    ; decimal exponent
```

Cover equality of numbers inc literal fractions and exponents

---

cts.json
tests/filter.json
tests/functions/length.json
tests/functions/match.json
tests/functions/search.json

These additional test cases cover using function expressions as function parameters, plus an additional `length()` case [mentioned in the spec](https://datatracker.ietf.org/doc/html/draft-ietf-jsonpath-base-21#name-examples-7).
Note that it's not currently possible to test `count()` and `value()` with function expressions as parameters using standard function extensions alone. None of the standard function extensions return a _NodesType_.
This PR partially replaces #51. See also the conversation on PR #51.

Cover function expressions as function parameters

---

README.md
cts.json
cts.schema.json
tests/basic.json

This is not necessarily an exhaustive set of tests of the non-deterministic features of RFC 9535. However, it establishes a convention for how to write such tests.
A non-deterministic test has a "results" key instead of a "result" key. The value corresponding to "results" is an array or possible results. If an implementation produces any one of these, the test should pass. If an implementation produces any other result, the test should fail.
Ref https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/issues/9

Introduce some tests of non-determinism

---

.github/workflows/build_cts_json.yaml
.github/workflows/update-cts-json.yaml
.github/workflows/validate_json_schema.yaml
CONTRIBUTING.md

Resolves #33
For every push to `main` the new workflow runs `build.sh` and afterwards commits & pushes the changes for `cts.json`, if any.
Example workflow runs:
- [No change](https://github.com/Marcono1234/jsonpath-compliance-test-suite/actions/runs/8052973356)
- [Change](https://github.com/Marcono1234/jsonpath-compliance-test-suite/actions/runs/8052985119) and commit https://github.com/Marcono1234/jsonpath-compliance-test-suite/commit/b01ffbb6ad4f3c9f24d1a4bcf0be2ff168905415
- [Change & unexpected change](https://github.com/Marcono1234/jsonpath-compliance-test-suite/actions/runs/8053015649)
Limitations:
- The push event for updating `cts.json` does not trigger any other workflows, see [action documentation](https://github.com/stefanzweifel/git-auto-commit-action/tree/master?tab=readme-ov …

Add GitHub workflow for updating `cts.json`

---

tests/filter.json

Add a test case for filtering object data, with nondeterministic ordering.

Add test for filtering object data

---

build.js

See https://www.typescriptlang.org/docs/handbook/intro-to-js-ts.html#ts-check
In VS Code this seems to automatically perform type checking then when viewing and editing the file. But this has no effect when using `build.sh` even when there are type errors, and is not checked by GitHub CI.
No worries if you don't want to include this change.

Enable type checking in `build.js` (for IDE)

---

tests/filter.json

Test that `&&` binds more tightly than `||`.
`$[?@.a || @.b && @.b]` is testing that `true || false && false` is equivalent to `(true || (false && false))`, which should evaluate to `true`.
`$[?@.b && @.b || @.a]` is testing that `false && false || true` is equivalent to `((false && false ) || true)`, which should evaluate to `true`. This should catch implementations that are inadvertently evaluating from right to left with equal precedence.
I had initially wanted to do `$[?true || false && false]`, but realised literal `true` and `false` are not a "basic-expr". So went with existence tests instead of `$[?true == true || false == false && false == false]`.

Test that `&&` binds more tightly than `||`

---

tests/filter.json

Test that singular filter queries are evaluated as existence tests when they are part of a logical expression, but not involving a comparison expression.
This was [a bug](https://github.com/jg-rp/python-jsonpath/issues/57) for me. I was eagerly unwrapping singular node lists before evaluating comparison expression **and** logical expressions.

Cover existence tests in logical expressions

---

tests/basic.json

The non-determinism in this case arises because of the interleaving of descendants allowed by RFC 9535 Section 2.5.2.2.
Note that there is more non-determinism in the ordering of descendants, but much of this is removed by the applications of the child wildcard ([*]).
The list of the input node and its descendants (the result of .. before [*] is applied) can be in any of these orders:
[[[[1]],[2]],[[1]],[1],[2],1,2]
[[[[1]],[2]],[[1]],[1],[2],2,1]
[[[[1]],[2]],[[1]],[1],1,[2],2]
[[[[1]],[2]],[[1]],[2],[1],1,2]
[[[[1]],[2]],[[1]],[2],[1],2,1]
[[[[1]],[2]],[[1]],[2],2,[1],1]
Notice that these all satisfy the rules in Section 2.5.2.2:
* nodes of any array are visited in array order, and
* nodes are visited before their descendants.
Ref: https://github.com/glyn/jsonpath-nondeterminism
/cc …

Add a non-deterministic test not involving objects

---

cts.json
tests/basic.json

The non-determinism comes from the descendant traversal ordering rules as well as from the unordered nature of objects.
(Please note that this was accidentally pushed to main earlier and then reverted. A branch protection rule is now in place!)

Add a nested object case with non-determinism

---

tests/filter.json

Unless I have overlooked something, the existing tests (code in the lines below my changes) was only covering invalid non-singular filters.
These tests also make sure that for example
- `?@[0, 0, 'a']` does not cause the result to contain duplicate values (despite the duplicate `0`)
- a slice such as `?@[0:2]` does not truncate the result if the array has more elements

Add filter tests for valid non-singular segment

---

tests/filter.json

It looks like the case `@==@` was previously not covered, but is mentioned in the RFC (as `$.a[?@ == @]`), so I thought it might be good to add it.
Please let me know what you think.

Add filter test for equality with self

---

cts.json
tests/functions/match.json
tests/functions/search.json

I-Regexp follows the [XSD-2](https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#regexs) which states that the equivalent character class for `.` is `[^\r\n]`. Some programming languages (e.g. Javascript, Dart) treat `.` differently, in particular it won't match Unicode chars `\u2029` and `\u2028`. This PR introduces a corresponding edge case test.

Add an edge case test that `.` matches \\u2029 and \\u2028

---

tests/functions/match.json
tests/functions/search.json

This PR covers some corner cases that might arise when mapping I-Regexp patterns to implementation-specific regex patterns.

Test I-Regexp mapping corner cases

---

tests/filter.json

Addresses https://github.com/gregsdennis/json-everything/issues/728

add quote escape tests for filter expressions

---

tests/filter.json

Test that filter expression literals must be compared, unless they're inside a function expression.

Test that filter expression literals must be compared

---

tests/filter.json

Found a few bugs in my implementation surrounding these, and discovered that the tests could be better.

improve boolean operator order of ops and grouping tests

---

tests/name_selector.json

Covers escape sequences which are allowed in some programming languages (e.g. [C++](https://en.cppreference.com/w/cpp/language/escape) and [Python](https://docs.python.org/3/reference/lexical_analysis.html#escape-sequences)), but which are not valid for JSONPath.
Also adds two test for incomplete `\u` escapes.
I only added these tests for double quoted selectors, but in theory they also apply to single quoted strings (and filters?). But I am not sure if it is really worth duplicating them.

Add more tests for invalid escape sequences

---

tests/name_selector.json

Adds tests for invalid surrogate pairs, and one test for directly using a character > U+FFFF (`𝄞`) in the selector, instead of escaping it.
----
Note: Another interesting test would be
- escaped + non-escaped surrogate character, for example: `"selector": "$[\"\\uD800\uDC00\"]"`
(for this a JSONPath implementation might erroneously first convert `\\uD800` to U+D800 before performing validation, and then consider this a valid surrogate pair)
- malformed non-escaped surrogate pairs, for example `"selector": "$[\"\uD800\uD800\"]"`
Note in both cases the single `\` instead of `\\`.
Both are not permitted by JSONPath because it says the query must be valid UTF-8, which is not the case here.
However, it depends on the programming language whether such malformed surrogate pairs are possible. For …

Add tests for invalid surrogate pairs

---

tests/name_selector.json

The JSONPath specification says only the control characters 0x00 to 0x1F must be escaped (same as for JSON). The control character 0x7F (DEL) does not have to be escaped.
However, some JSON libraries are too strict and reject a non-escaped 0x7F, see also https://github.com/nst/JSONTestSuite/issues/118.
Therefore this test makes sure JSONPath implementations don't make the same error.

Add test for non-escaped U+007F (DEL control character)

---

tests/filter.json

Generally for number literals since JSONPath uses the same syntax as JSON, test values from regular JSON libraries or JSON test suites could be used, for example https://github.com/nst/JSONTestSuite.
So if you have anything else in mind which should be covered, please let me know or feel free to add it yourself.

Add tests for invalid and uncommon filter literal values

---

tests/basic.json
tests/index_selector.json
tests/slice_selector.json

The "min exact" and "max exact" values here are based on the "range of exact integer values defined in Internet JSON (I-JSON)", as required by the JSONPath specification for index and slice selectors.
I have kept the existing overflow tests because they might still be useful to test overflow during parsing, which might happen before the "range of exact integer values" check in JSONPath implementations.
To be safe, could you please check how your JSONPath implementations behave, to make sure I did not overlook something.

Add more tests for selectors

---

build.js
tests/whitespace/selectors.json

Inspired by https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/issues/36#issuecomment-1523515817
Due to copy & paste errors there were already duplicate names in `selectors.json`, see changes below.
Not sure if the change in `build.js` clean enough, please let me know if I should change it in some way.

Check for duplicate test names

---

tests/filter.json

I think these are sufficient for my test coverage for now. I might add more in the future if need be.
Related #72.

Add absolute path filter tests

---

tests/filter.json

With my current implementation, I am skipping function tests based on tags. A couple tests were missing the `function` tag. Hence added in this PR. This would also help me in submoduling the repository instead of testing on a locally patched `cts.json`.

Add missing function tags

---

tests/filter.json
tests/slice_selector.json

Add test slice selector followed by slice selector
Add test filter selector followed by child segment that selects multiple elements
Add test filter selector followed by name selector

Add tests of selector that follows another selector.  Resolves #96

---

tests/basic.json
tests/filter.json
tests/slice_selector.json

A few more tests:
* filter selector,  non-matching name and index selectors are equal within a comparison
* array slice selector, test negative start and end indexes with positive step
* invalid selector tests for using @ and $ outside of filter expression
There is already an array slice selector test `$[-1:-3]` with negative start and end, but that one returns no results because the default step doesn't go in the right direction (ie. from start index to end index.)
The point of this new test is that it is a negative start/end query that actually returns values.

Additional filter and array slice selector tests

---

tests/basic.json

Section 2.5.1.1 defines shorthand names with this grammar:
```anbf
member-name-shorthand = name-first *name-char
name-first          = ALPHA /
"_"   /
%x80-D7FF /
; skip surrogate code points
%xE000-10FFFF
name-char           = name-first / DIGIT
```
This allows shorthand names that correspond to the JSON literals `true`, `false`, and `null`.
So add tests for this pattern.

Test JSON bool, null literal shorthand names

---

cts.json
tests/functions/length.json

There is a test for ValueType function-arguments that reference a non-singulary query with wildcard.
But no such test for index-selectors with multiple indices nor for name-selectors with multiple names.
Adding one test of each type which will show an error in the query.

Add ValueType function-argument singular query tests
